stages:
  - install
  - validate
  - build
  - deploy

cache:
  paths:
    - '**/node_modules'

variables:
  DOCKER_IMAGE: 'cr.yandex/$REGISTRY_ID/node-server:latest'

# FRONTEND
install_frontend:
  stage: install
  image: node:20
  script:
    - echo "Installing frontend dependencies"
    - cd frontend && npm ci
  artifacts:
    paths:
      - frontend/node_modules
      - frontend/package-lock.json
  rules:
    - changes:
        - frontend/**

prettier-check_frontend:
  stage: validate
  image: node:20
  dependencies:
    - install_frontend
  script:
    - echo "Prettier checking frontend"
    - cd frontend && npm run format
  rules:
    - changes:
        - frontend/**

lint-test_frontend:
  stage: validate
  image: node:20
  dependencies:
    - install_frontend
  script:
    - echo "Linting frontend"
    - cd frontend && npm run lint
  rules:
    - changes:
        - frontend/**

stylelint-test_frontend:
  stage: validate
  image: node:20
  dependencies:
    - install_frontend
  script:
    - echo "Stylelinting frontend"
    - cd frontend && npm run stylelint
  rules:
    - changes:
        - frontend/**

unit-test_frontend:
  stage: validate
  image: node:20
  dependencies:
    - install_frontend
  script:
    - echo "Unit testing frontend"
    - cd frontend && npm run test
  rules:
    - changes:
        - frontend/**

integration-test_frontend:
  stage: validate
  image: mcr.microsoft.com/playwright:v1.40.0-focal
  dependencies:
    - install_frontend
  script:
    - echo "Installing Playwright browsers"
    - npx playwright install --with-deps
    - echo "Running frontend server"
    - cd frontend && npm run dev &
    - echo "Waiting for the server to start"
    - |
      for i in {1..30}; do
        if curl -s http://localhost:5173; then
          break
        fi
        echo "Waiting for server..."
        sleep 1
      done
    - echo "Running integration tests"
    - cd frontend && npm run integration
  artifacts:
    paths:
      - frontend/test-results/
    expire_in: 1 week
  rules:
    - changes:
        - frontend/**

# BACKEND
install_backend:
  stage: install
  image: node:20
  script:
    - echo "Installing backend dependencies"
    - cd backend && yarn install
  artifacts:
    paths:
      - backend/node_modules
      - backend/yarn.lock
  rules:
    - if: '$CI_COMMIT_BRANCH == "back-dev"'

prettier-check_backend:
  stage: validate
  image: node:20
  dependencies:
    - install_backend
  script:
    - echo "Prettier checking backend"
    - cd backend && yarn format
  rules:
    - if: '$CI_COMMIT_BRANCH == "back-dev"'

lint-test_backend:
  stage: validate
  image: node:20
  dependencies:
    - install_backend
  script:
    - echo "Linting backend"
    - cd backend && yarn lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "back-dev"'

build_docker:
  stage: build
  image: docker
  services:
    - docker:dind
  only:
    - master
  script:
    - docker-compose build
    - echo $OAuth|docker login --username oauth --password-stdin cr.yandex
    - docker tag node-server $DOCKER_IMAGE
    - docker push $DOCKER_IMAGE

deploy_docker:
  stage: deploy
  only:
    - master
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IP_ADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh $SSH_USER@$VM_IP_ADDRESS
