services:
  node-server:
    build:
      context: ..
      dockerfile: docker/server.Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ../backend/.env.sample
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ../backend/.env.sample

# docker compose -f ./docker/docker-compose.yml -p docker up -d
# docker ps
# docker exec -it 9a512db803a0 sh
# node dist/prisma/seed.js